In [2]:
import numpy as np

##create arrays using numpy
##create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

shape = arr1.shape
print(shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [5]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
my_list = [[1,2,3,4,5],[1,2,3]]
my_list

# np.array([[1,2,3,4,5],[1,2,3]]) #not possible

[[1, 2, 3, 4, 5], [1, 2, 3]]

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
#inbuilt functions
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr) #prints the array
print(arr.shape) #shape of the array
print(arr.ndim) #dimension of the array
print(arr.size) #size of the array
print(arr.dtype) #data type
print(arr.itemsize) #item size (in bytes)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [11]:
#Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise addition
print(arr1+arr2)

#Element wise substraction
print(arr1-arr2)

#Return type will be an array

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]


In [12]:
#Universal functions
arr=np.array([1,2,3,4,5,6])

print(np.sqrt(arr)) #square root

print(np.exp(arr)) #exponential

print(np.sin(arr)) #sine

print(np.log(arr)) #natural log

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
#Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(arr[1][1]) 

print(arr[1:,2:])

print(arr[:2,2:])

print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [14]:
#Modify array element
arr[0,0] = 100
print(arr)

arr[1:]= 0
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  0   0   0   0]
 [  0   0   0   0]]


In [15]:
#STATISTICAL CONCEPTS - Normalization (mean 0, SD 1)

#To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [16]:
#More:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [17]:
#Logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

Pandas from here!

In [18]:
import pandas as pd

In [19]:
# Series (one dimensional array-like object)

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [20]:
# Create a Series from dictionary
data ={'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)


a    1
b    2
c    3
dtype: int64


In [21]:
data = [10,20,30]
index=['a','b','c']
pd.Series(data, index=index)


a    10
b    20
c    30
dtype: int64

In [22]:
# Dataframe (two dimensional (Table))
# create a Dataframe from a dictionary of list

data ={
    'Name':['Utkarsh','Prakash','Aditya'],
    'Age':[25,30,45],
    'City':['Bangalore','Pune','Hyderabad']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Utkarsh   25  Bangalore
1  Prakash   30       Pune
2   Aditya   45  Hyderabad
<class 'pandas.core.frame.DataFrame'>


In [23]:
import numpy as np
np.array(df)


array([['Utkarsh', 25, 'Bangalore'],
       ['Prakash', 30, 'Pune'],
       ['Aditya', 45, 'Hyderabad']], dtype=object)

In [24]:
# Createa a Data frame from a list of dictionaries

data =[
    {'Name':'Utkarsh','Age':32,'City':'Bangalore'},
    {'Name':'Prakash','Age':24,'City':'Pune'},
    {'Name':'Aditya','Age':36,'City':'Hyderabad'},
    {'Name':'Sumit','Age':28,'City':'Mumnai'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Utkarsh   32  Bangalore
1  Prakash   24       Pune
2   Aditya   36  Hyderabad
3    Sumit   28     Mumnai
<class 'pandas.core.frame.DataFrame'>


In [25]:
df = pd.read_csv('sales_data.csv')
df.head(5)
# df.tail(5)

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [26]:
# Accessing Data from Dataframe
data ={
    'Name':['Utkarsh','Prakash','Aditya'],
    'Age':[25,30,45],
    'City':['Bangalore','Pune','Hyderabad']
}

df=pd.DataFrame(data)
df

Name  Age       City
0  Utkarsh   25  Bangalore
1  Prakash   30       Pune
2   Aditya   45  Hyderabad

In [27]:
print(df['City'])
type(df['Name'])

print(df.loc[0]) #here 0 is index location
print(df.loc[2])

0    Bangalore
1         Pune
2    Hyderabad
Name: City, dtype: object
Name      Utkarsh
Age            25
City    Bangalore
Name: 0, dtype: object
Name       Aditya
Age            45
City    Hyderabad
Name: 2, dtype: object


In [28]:
print(df)

print(df.iloc[0])

print(df.loc[0])

      Name  Age       City
0  Utkarsh   25  Bangalore
1  Prakash   30       Pune
2   Aditya   45  Hyderabad
Name      Utkarsh
Age            25
City    Bangalore
Name: 0, dtype: object
Name      Utkarsh
Age            25
City    Bangalore
Name: 0, dtype: object


In [29]:
# Accessing a specified element

print(df)
print(df.at[1,'Age']) #(index, column)
print(df.at[2,'Age'])

      Name  Age       City
0  Utkarsh   25  Bangalore
1  Prakash   30       Pune
2   Aditya   45  Hyderabad
30
45


In [30]:
df.iat[2,2] #(location)

'Hyderabad'

Data manipulations with Dataframe

In [31]:
# Add a column

df['Salary'] = [50000,60000,70000]
df

Name  Age       City  Salary
0  Utkarsh   25  Bangalore   50000
1  Prakash   30       Pune   60000
2   Aditya   45  Hyderabad   70000

In [32]:
# Remove a column

df.drop('Salary', axis = 1, inplace=True) 
#Axsi => row = 1, default-column = 0

In [33]:
df

Name  Age       City
0  Utkarsh   25  Bangalore
1  Prakash   30       Pune
2   Aditya   45  Hyderabad

In [34]:
# Add age to the column

df['Age'] = df['Age']+1
df

Name  Age       City
0  Utkarsh   26  Bangalore
1  Prakash   31       Pune
2   Aditya   46  Hyderabad

In [35]:
df.drop(0, inplace=True) # Drops 0 indexed column
df

Name  Age       City
1  Prakash   31       Pune
2   Aditya   46  Hyderabad

DATA MANIPULATION WITH PANDAS

In [36]:
df = pd.read_csv('data.csv')
# fetch the first 5 rows
df.head(5)

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [37]:
df.tail(5)

Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [38]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [39]:
df.dtypes #object = string


Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [40]:
# Handeling missing values

df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [41]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [42]:
df_filled = df.fillna(0)

In [43]:
# filling missing values with the mean of the column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [44]:
# Renaming columns

df = df.rename(columns={'Date':'Sales Date'})
df.head()

Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [45]:
# Change datatypes
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

Sales Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [46]:
df['New Value'] = df['Value'].apply(lambda x:x*2)

In [47]:
df.head()

Sales Date Category  Value   Product  Sales Region  Sales_fillNA  \
0  2023-01-01        A   28.0  Product1  754.0   East         754.0   
1  2023-01-02        B   39.0  Product3  110.0  North         110.0   
2  2023-01-03        C   32.0  Product2  398.0   East         398.0   
3  2023-01-04        B    8.0  Product1  522.0   East         522.0   
4  2023-01-05        B   26.0  Product3  869.0  North         869.0   

   Value_new  New Value  
0         28       56.0  
1         39       78.0  
2         32       64.0  
3          8       16.0  
4         26       52.0

In [48]:
# Data Aggregating and Grouping
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64


In [51]:
df.groupby(['Product','Region'])['Value'].sum()

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [53]:
# Aggregate multiple finctions

grouped_agd = df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agd

mean     sum  count
Region                          
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [54]:
# Merging and joining Dataframes

# Sample DataFrames
df1 = pd.DataFrame({'Key': ['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key': ['A','B','D'], 'Value1':[4,5,6]})

In [58]:
df1

Key  Value1
0   A       1
1   B       2
2   C       3

In [59]:
df2

Key  Value1
0   A       4
1   B       5
2   D       6

In [61]:
# Merge DataFrame on the 'Key Columns'
pd.merge(df1, df2, on="Key", how="inner")

Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [64]:
pd.merge(df1, df2, on="Key", how="left")

Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN