In [ ]:
!pip install numpy

In [7]:
import numpy as np

##create arrays using numpy
##create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

shape = arr1.shape
print(shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [9]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [13]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
my_list = [[1,2,3,4,5],[1,2,3]]
my_list

np.array([[1,2,3,4,5],[1,2,3]]) #not possible

In [20]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
#inbuilt functions
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr) #prints the array
print(arr.shape) #shape of the array
print(arr.ndim) #dimension of the array
print(arr.size) #size of the array
print(arr.dtype) #data type
print(arr.itemsize) #item size (in bytes)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [ ]:
#Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise addition
print(arr1+arr2)

#Element wise substraction
print(arr1-arr2)

#Return type will be an array

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]


In [ ]:
#Universal functions
arr=np.array([1,2,3,4,5,6])

print(np.sqrt(arr)) #square root

print(np.exp(arr)) #exponential

print(np.sin(arr)) #sine

print(np.log(arr)) #natural log

In [60]:
#Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(arr[1][1]) 

print(arr[1:,2:])

print(arr[:2,2:])

print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [62]:
#Modify array element
arr[0,0] = 100
print(arr)

arr[1:]= 0
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  0   0   0   0]
 [  0   0   0   0]]


In [64]:
#STATISTICAL CONCEPTS - Normalization (mean 0, SD 1)

#To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [65]:
#More:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25
